# Generated by Django 5.1.3 on 2025-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pregunta', models.TextField()),
                ('tipo_respuesta', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('dos_opciones', 'Dos Opciones'), ('respuesta_abierta', 'Respuesta Abierta')], max_length=20)),
                ('opciones', models.TextField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
