# Generated by Django 5.1.3 on 2025-01-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0003_encuesta_delete_encuestas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='respuesta',
        ),
    ]
