# Generated by Django 5.1.3 on 2025-01-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0004_remove_encuesta_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('pregunta_tipo', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Encuestas.form')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Encuestas.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
    ]
